[tool.commitizen]
version = "0.6.3"
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version → $new_version [skip-ci]"
version_files = ["pyproject.toml:version", "src/gcon/__version__.py:version"]
